### ISSUE TITLE
Issue #1 occurs again.

### ISSUE THREAD

**Issue by s-shin** [steelbrain/package-deps#25]
The error reported in https://github.com/steelbrain/package-deps/issues/1 seems to be generated again.
My code can be found in https://github.com/s-shin/linter-perl/pull/22.

v3.0.0:
<img width="943" alt="v3 0 0" src="https://cloud.githubusercontent.com/assets/1000800/11065052/785f812e-8804-11e5-8c19-ab1711d4f4e8.png">

v2.1.3:
<img width="943" alt="v2 1 3" src="https://cloud.githubusercontent.com/assets/1000800/11065054/7d4cdac4-8804-11e5-8fb5-bd8b87fb0846.png">

**Comment by steelbrain** [comment]
Ah man, it's an atom race condition issue, I'll ask around in slack and
talk about getting it fixed in the core. Until then I'll "work around" this
by waiting 20 miliseconds after the notification is created to get the view

On 10 November 2015 at 06:51, Seki, Shintaro <notifications@github.com>
wrote:

> The error reported in #1
> <https://github.com/steelbrain/package-deps/issues/1> seems to be
> generated again.
> My code can be found in s-shin/linter-perl#22
> <https://github.com/s-shin/linter-perl/pull/22>.
>
> v3.0.0:
> [image: v3 0 0]
> <https://cloud.githubusercontent.com/assets/1000800/11065052/785f812e-8804-11e5-8c19-ab1711d4f4e8.png>
>
> v2.1.3:
> [image: v2 1 3]
> <https://cloud.githubusercontent.com/assets/1000800/11065054/7d4cdac4-8804-11e5-8fb5-bd8b87fb0846.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/steelbrain/package-deps/issues/25>.
>



-- 
Regards,
Anees Iqbal - (92)312-6522996
