### ISSUE TITLE
Move package-deps to `apm`

### ISSUE THREAD

**Issue by aminya** [steelbrain/package-deps#269]
Now every package loads a separate instance of `package-deps` in their `node_modules`. This means a huge lag when we consider all of the Atom packages together.

The most logical approach for Atom is to merge the functionality of this package to `apm` and let `apm` do all of the dependency management offline once a package is installed. That is how every good Package manager does its job.

It does not make sense to care about installing dependencies in the runtime inside `activate` function.

**Comment by Arcanemagus** [comment]
We know the problems and where this needs to be solved for everyone... but have been pushing for it to be solved there for _years_. You can see the last large attempt at this in https://github.com/atom/apm/pull/385 and the linked issues. This package was created as a workaround to get the functionality done in one place instead of rewriting it in every single package that needs it.

**Comment by aminya** [comment]
But is this issue solved? Why are we closing it?

**Comment by Arcanemagus** [comment]
This issue has **nothing** to do with `atom-package-deps`, where you opened it. This is an Atom issue.
