### ISSUE TITLE
Rename key to packageDeps

### ISSUE THREAD

**Issue by idleberg** [steelbrain/package-deps#82]
I recently had an edge case, in which I would have loved the option to use the following in my package:

```js
import { package-deps as atomDeps } from '../package.json'
```

Unfortunately, this does not work because of the hyphen in `package-deps` (and I couldn't find a workaround on MDN or Stack Overflow – quotes produce an error!) Maybe you could keep this in the back of your head, when working on a new major version with (other) breaking changes and rename this to `packageDeps` or `atomPackageDeps`.

As I said, this is an edge-case, so priority is low.

**Comment by steelbrain** [comment]
Hi @idleberg!

Here's what you can do to read the deps from your manifest

```
import manifest from '../package.json'

console.log(manifest['package-deps'])
```

The change you suggest will be an API breaking change one as you mentioned, but in my humble opinion the change is not worth breaking all the tons of packages depending on this module, when the edge case can be fixed with just two lines of code.

Let me know what you think

**Comment by idleberg** [comment]
That's what I'm using right now. And I agree that it might not be worth it.

**Comment by steelbrain** [comment]
Glad you agree with me @idleberg :)
