### ISSUE TITLE
Bump major and enable show prompt by default

### ISSUE THREAD

**Issue by steelbrain** [steelbrain/package-deps#85]
Most people didn't notice the new feature, or didn't read the new README to know that we've added a confirmation box, bumping major and setting it default would enable it for masses

**Comment by Arcanemagus** [comment]
Personally? I would say no, as virtually all of the use I have of this library is to ensure that linter providers have `linter` installed for the user. As they are absolutely useless without it, I'm not sure prompting them every time would be a good idea. Maybe if the prompt only prompts for things that aren't already installed (does it work this way already?)?

There are a few providers that currently are using this to install `linter` _and_ a language associated with the files they support, which should probably be prompting but aren't currently as they started using this before prompting was a thing.

As a counterpoint to all of that, letting users have the choice is a good thing.

So... I would be fine if it didn't prompt for things that are already installed, otherwise I'm not sure I'd say it should be a default.

**Comment by steelbrain** [comment]
It only shows the notification if the some or all dependencies are NOT installed. It will not show any kind-of notification if all dependencies of a module are already installed

**Comment by Arcanemagus** [comment]
I guess I would be fine with it being enabled by default then. I'm not actually sure I would consider it a breaking change either, as it's just a "new" feature that doesn't prevent using the package in the manner it already has been used.

**Comment by sonicdoe** [comment]
For what it’s worth, I’d suggest bumping the major version number next time. [From the Atom Flight Manual](http://flight-manual.atom.io/hacking-atom/sections/publishing/#publish-your-package) (emphasis mine):

> Use `major` when you make a change that breaks backwards compatibility, like **changing defaults** or removing features.
